name: Build Docker Image
on:
  workflow_run:
    workflows:
      - "Build Test Release"
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

jobs:
  build-prod-docker-image:
    name: Build docker image for users
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate in GitHub docker registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

      - name: Build docker image
        run: |
          docker build \
            --tag docker.pkg.github.com/$GITHUB_REPOSITORY/dbload:latest \
            .

      - name: Push image to GitHub docker registry
        run: |
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/dbload:latest